# Generated by Django 2.1.5 on 2023-03-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rango', '0002_delete_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('author', models.CharField(max_length=128)),
                ('date', models.DateField(null=True)),
                ('description', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
    ]
